title: "남도균"
description: "Software Convergence Student · Developer in Progress"

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      layout: splash
